### Test GET request
GET http://localhost:3000/api/test1
Accept: application/json

###

### Test PATCH request
PATCH http://localhost:3000/api/test1
Content-Type: application/json

{
  "userId": "1",
  "newUsername": "NewJohnDoe"
}

###

### Test DELETE request
DELETE http://localhost:3000/api/test1?userId=1
Accept: application/json


### Test the POST request to the API route
POST http://localhost:3000/api/bot
Content-Type: application/json

{
  "text": "Explain how AI works"
}