### Test Signup POST request
POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
  "name": "Test User",
  "email": "testuser@example.com",
  "username": "testuser",
  "password": "TestPassword123!",
  "teamname": "TestTeam"
}

###